/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-07-31 10:41:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._02ImplicitObject;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class RequestMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head><title>내장 객체 - request</title></head>\n");
      out.write("<body>\n");
      out.write("    <h2>1. 클라이언트와 서버의 환경정보 읽기</h2>\n");
      out.write("    <a href=\"./RequestWebInfo.jsp?eng=Hello&han=안녕\">  <!--GET 방식으로 요청-->\n");
      out.write("      GET 방식 전송\n");
      out.write("    </a>\n");
      out.write("    <br />\n");
      out.write("    <form action=\"RequestWebInfo.jsp\" method=\"post\">  <!--POST 방식으로 요청-->\n");
      out.write("        영어 : <input type=\"text\" name=\"eng\" value=\"Bye\" /><br />\n");
      out.write("        한글 : <input type=\"text\" name=\"han\" value=\"잘 가\" /><br />\n");
      out.write("        <input type=\"submit\" value=\"POST 방식 전송\" />\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <h2>2. 클라이언트의 요청 매개변수 읽기</h2>\n");
      out.write("    <form method=\"post\" action=\"RequestParameter.jsp\">  <!--다양한 <input> 태그 사용-->\n");
      out.write("        아이디 : <input type=\"text\" name=\"id\" value=\"\" /><br />\n");
      out.write("        성별 :\n");
      out.write("        <input type=\"radio\" name=\"sex\" value=\"man\" />남자\n");
      out.write("        <input type=\"radio\" name=\"sex\" value=\"woman\" checked=\"checked\" />여자\n");
      out.write("        <br />\n");
      out.write("        관심사항 :\n");
      out.write("        <input type=\"checkbox\" name=\"favo\" value=\"eco\" />경제\n");
      out.write("        <input type=\"checkbox\" name=\"favo\" value=\"pol\" checked=\"checked\" />정치\n");
      out.write("        <input type=\"checkbox\" name=\"favo\" value=\"ent\" />연예<br />\n");
      out.write("        자기소개:\n");
      out.write("        <textarea name=\"intro\" cols=\"30\" rows=\"4\"></textarea>\n");
      out.write("        <br />\n");
      out.write("        <input type=\"submit\" value=\"전송하기\" />\n");
      out.write("    </form>\n");
      out.write("\n");
      out.write("    <h2>3. HTTP 요청 헤더 정보 읽기</h2>\n");
      out.write("    <a href=\"RequestHeader.jsp\">  <!--HTTP 요청 헤더 읽기-->\n");
      out.write("        요청 헤더 정보 읽기\n");
      out.write("    </a>    \n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
